/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.mapstruct.mapstruct)
    api(libs.org.mapstruct.mapstruct.processor)
    api(libs.org.projectlombok.lombok)
    api(libs.org.projectlombok.lombok.mapstruct.binding)
}

group = "org.example"
version = "1.0-SNAPSHOT"
description = "18_maven"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
